import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { resolve } from 'path'
import fg from 'fast-glob'

// Discover every route/**/index.html on disk so new article pages
// (generated by src/scripts/generate-routes.js) don't need manual entries here.
const routeEntries = fg.sync('route/**/index.html', { cwd: __dirname })

const input = { main: resolve(__dirname, 'index.html') }
for (const file of routeEntries) {
  const key = file.replace(/\/index\.html$/, '').replace(/\//g, '-')
  input[key] = resolve(__dirname, file)
}

// https://vite.dev/config/
export default defineConfig({
  base: '/',
  plugins: [react()],
  build: {
    rollupOptions: {
      input,
    },
  },
})
